### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 

### ISSUE THREAD

**Issue by dikubab** [CodeAchieveDream/ocr_generate_text_data#4]
when I replace the fonts with different fonts I have got an error.  why could this possibly be? can remove fanti from the code?

Traceback (most recent call last):
  File "main.py", line 184, in <module>
    local_font = LocalFont()
  File "//localfont.py", line 14, in __init__
    self.all_font = self.get_all_font(self.path)
  File "/localfont.py", line 29, in get_all_font
    font_txt = open(os.path.join(path, font), 'r').read()
  File "/Users//opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 11: invalid start byte

**Comment by CodeAchieveDream** [comment]
this（UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 11: invalid start byte） error，you can use "open('a.txt', 'r', encoding='utf-8 or gbk').read()" take a try，fanti is make traditional Chinese data，according to you project，you can comment this code
the project can use different font make training data for text recognition


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "CodeAchieveDream/ocr_generate_text_data"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月25日(星期天) 晚上6:33
收件人:&nbsp;"CodeAchieveDream/ocr_generate_text_data"<ocr_generate_text_data@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[CodeAchieveDream/ocr_generate_text_data] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0  (#4)





 
when I replace the fonts with different fonts I have got an error.  why could this possibly be? can remove fanti from the code?
 
Traceback (most recent call last):
 File "main.py", line 184, in 
 local_font = LocalFont()
 File "//localfont.py", line 14, in init
 self.all_font = self.get_all_font(self.path)
 File "/localfont.py", line 29, in get_all_font
 font_txt = open(os.path.join(path, font), 'r').read()
 File "/Users//opt/anaconda3/lib/python3.8/codecs.py", line 322, in decode
 (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 11: invalid start byte
